apiVersion: 1
datasources:
  - name: $POSTGRES_DB
    type: postgres
    access: proxy
    url: climacan-postgres:$PGPORT
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: "disable"  # No se usa SSL
      postgresVersion: 1500
      timescaledb: false  # Extension para datos temporales
    editable: false
