{
 "title": "Hourly Forecast by Municipality",
 "time": { "from": "now-24h", "to": "now+3d" },
 "templating": {
  "list": [
   {
    "name": "Municipality",
    "label": "Municipio",
    "query": "SELECT nombre FROM municipios_canarios"
   },
   {
    "name": "altitud",
    "query": "SELECT \n  altitud\nFROM municipios_canarios\nWHERE nombre = '$Municipality';"
   },
   {
    "name": "id",
    "query": "SELECT \n  id\nFROM municipios_canarios\nWHERE nombre = '$Municipality';"
   },
   {
    "name": "num_hab",
    "query": "SELECT \n  num_hab\nFROM municipios_canarios\nWHERE nombre = '$Municipality';"
   },
   {
    "name": "zona_comarcal",
    "query": "SELECT \n  zona_comarcal\nFROM municipios_canarios\nWHERE nombre = '$Municipality';"
   },
   {
    "name": "latitud_dec",
    "query": "SELECT \n  latitud_dec\nFROM municipios_canarios\nWHERE nombre = '$Municipality';"
   },
   {
    "name": "longitud_dec",
    "query": "SELECT \n  longitud_dec\nFROM municipios_canarios\nWHERE nombre = '$Municipality';"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; width: 100%; height: 100%; align-items: center; padding: 20px; box-shadow: none; border-radius: 8px;\">\n  <!-- Content of the table (left side) -->\n  <div style=\"flex: 3; padding-right: 20px;\">\n    <h2 style=\"color: #336699; padding-bottom: 10px;\">Información de la Estación</h2>\n    <p style=\"margin: 10px 0;\"><strong style=\"color: #336699; font-size: 1.1em;\">ID:</strong> ${id}</p>\n    <p style=\"margin: 10px 0;\"><strong style=\"color: #336699; font-size: 1.1em;\">Altitud (relativa al nivel del mar):</strong> ${altitud} m</p>\n    <p style=\"margin: 10px 0;\"><strong style=\"color: #336699; font-size: 1.1em;\">Zona Comarcal:</strong> ${zona_comarcal}</p>\n    <p style=\"margin: 10px 0;\"><strong style=\"color: #336699; font-size: 1.1em;\">Numero Habitantes:</strong> ${num_hab}</p>\n    <p style=\"margin: 20px 0;\">\n      <a href=\"https://www.google.com/maps/search/?api=1&query=${latitud_dec},${longitud_dec}\" target=\"_blank\" \n         style=\"color: #ffffff; background-color: #336699; padding: 10px 15px; text-decoration: none; border-radius: 5px; \n                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3), 0 1px 3px rgba(255, 204, 0, 0.5); \n                transition: background-color 0.3s ease, color 0.3s ease, box-shadow 0.3s ease;\"\n         onmouseover=\"this.style.backgroundColor='#4a80c2'; this.style.color='#e8f0ff'; this.style.boxShadow='0 6px 12px rgba(0, 0, 0, 0.4), 0 2px 4px rgba(255, 204, 0, 0.6)';\"\n         onmouseout=\"this.style.backgroundColor='#336699'; this.style.color='white'; this.style.boxShadow='0 4px 8px rgba(0, 0, 0, 0.3), 0 1px 3px rgba(255, 204, 0, 0.5)';\">\n         Ver en Google Maps\n      </a>\n    </p>\n  </div>\n  <!-- Image (right side) -->\n  <div style=\"flex: 2; display: flex; justify-content: flex-end; align-items: center;\">\n    <img src=\"/public/my_img/logo-climacan.png\" alt=\"Climacan Logo\" \n         style=\"width: 250px; height: 250px; object-fit: contain; filter: drop-shadow(4px 4px 6px rgba(0, 0, 0, 0.5));\">\n  </div>\n</div>\n"
   }
  },
  {
   "title": "Precipitación",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "alias": "Precipitación",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "precipitacion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Prob. Precipitación",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "probPrecipitacion",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Prob. Tormenta",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "probTormenta",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperatura",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperatura",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Sensación Térmica",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensTermica",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humedad Relativa",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Humedad Relativa",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humedadRelativa",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nieve",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "alias": "Nieve",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nieve",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Prob. Nieve",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "probNieve",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Viento",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "alias": "Dirección del viento",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vientoAndRachaMax",
     "select": [
      [
       { "params": [ "direccion_degrees" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Velocidad",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vientoAndRachaMax",
     "select": [
      [
       { "params": [ "velocidad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Velocidad Máx.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vientoAndRachaMax",
     "select": [
      [
       { "params": [ "velocidad_max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estado del cielo",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "alias": "Estado del cielo",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "estadoCielo",
     "select": [
      [
       { "params": [ "descripcion" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}